drop view if exists public.products;
drop table if exists public.listing_highlights cascade;
drop table if exists public.listing_images cascade;
drop table if exists public.listings cascade;
drop table if exists public.listing_conditions cascade;
drop table if exists public.sellers cascade;
drop table if exists public.categories cascade;

create table public.categories (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null unique,
  created_at timestamptz not null default now()
);

create table public.sellers (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  store_name text not null,
  location text not null,
  phone text,
  created_at timestamptz not null default now()
);

create table public.listing_conditions (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null unique,
  created_at timestamptz not null default now()
);

create table public.listings (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  title text not null,
  category_id bigint not null references public.categories (id) on update cascade on delete restrict,
  seller_id bigint not null references public.sellers (id) on update cascade on delete restrict,
  condition_id bigint not null references public.listing_conditions (id) on update cascade on delete restrict,
  price integer not null check (price >= 0),
  location text not null,
  production_year text not null,
  description text not null,
  is_active boolean not null default true,
  source_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.listing_images (
  id bigint generated by default as identity primary key,
  listing_id bigint not null references public.listings (id) on update cascade on delete cascade,
  url text not null,
  alt_text text,
  display_order integer not null default 0,
  is_primary boolean not null default false,
  created_at timestamptz not null default now(),
  unique (listing_id, url)
);

create table public.listing_highlights (
  id bigint generated by default as identity primary key,
  listing_id bigint not null references public.listings (id) on update cascade on delete cascade,
  value text not null,
  display_order integer not null default 0,
  created_at timestamptz not null default now(),
  unique (listing_id, value)
);

create index categories_slug_idx on public.categories (slug);
create index sellers_slug_idx on public.sellers (slug);
create index listing_conditions_slug_idx on public.listing_conditions (slug);
create index listings_slug_idx on public.listings (slug);
create index listings_category_id_idx on public.listings (category_id);
create index listings_seller_id_idx on public.listings (seller_id);
create index listings_condition_id_idx on public.listings (condition_id);
create index listing_images_listing_id_idx on public.listing_images (listing_id);
create index listing_highlights_listing_id_idx on public.listing_highlights (listing_id);

alter table public.categories enable row level security;
alter table public.sellers enable row level security;
alter table public.listing_conditions enable row level security;
alter table public.listings enable row level security;
alter table public.listing_images enable row level security;
alter table public.listing_highlights enable row level security;

create policy "Categories are publicly readable" on public.categories
for select to anon, authenticated using (true);

create policy "Sellers are publicly readable" on public.sellers
for select to anon, authenticated using (true);

create policy "Listing conditions are publicly readable" on public.listing_conditions
for select to anon, authenticated using (true);

create policy "Active listings are publicly readable" on public.listings
for select to anon, authenticated using (is_active = true);

create policy "Listing images are publicly readable" on public.listing_images
for select to anon, authenticated using (true);

create policy "Listing highlights are publicly readable" on public.listing_highlights
for select to anon, authenticated using (true);

create or replace view public.products
with (security_invoker = true)
as
select
  listings.id,
  listings.slug,
  listings.title as name,
  categories.name as category,
  listing_conditions.name as condition,
  listings.price,
  listings.location,
  coalesce(primary_image.url, gallery_images.gallery[1], '/logo-pojok-seken.svg') as image,
  coalesce(gallery_images.gallery, array[]::text[]) as gallery,
  listings.production_year as year,
  sellers.store_name as seller,
  listings.description,
  coalesce(listing_highlight_values.highlights, array[]::text[]) as highlights,
  listings.source_url
from public.listings
join public.categories on categories.id = listings.category_id
join public.sellers on sellers.id = listings.seller_id
join public.listing_conditions on listing_conditions.id = listings.condition_id
left join lateral (
  select listing_images.url
  from public.listing_images
  where listing_images.listing_id = listings.id
  order by listing_images.is_primary desc, listing_images.display_order asc, listing_images.id asc
  limit 1
) primary_image on true
left join lateral (
  select array_agg(listing_images.url order by listing_images.display_order asc, listing_images.id asc) as gallery
  from public.listing_images
  where listing_images.listing_id = listings.id
) gallery_images on true
left join lateral (
  select array_agg(listing_highlights.value order by listing_highlights.display_order asc, listing_highlights.id asc) as highlights
  from public.listing_highlights
  where listing_highlights.listing_id = listings.id
) listing_highlight_values on true
where listings.is_active = true;

grant select on public.products to anon, authenticated;
