create table if not exists public.scraped_products (
  id bigint generated by default as identity primary key,
  source text not null,
  source_label text not null,
  source_url text not null,
  image_url text not null,
  title text not null,
  description text not null default '',
  price bigint check (price is null or price >= 0),
  price_text text not null default '',
  detail_url text not null unique,
  raw jsonb not null default '{}'::jsonb,
  scraped_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists scraped_products_source_idx on public.scraped_products (source);
create index if not exists scraped_products_scraped_at_idx on public.scraped_products (scraped_at desc);
create index if not exists scraped_products_title_idx on public.scraped_products using gin (to_tsvector('simple', title));

create or replace function public.set_scraped_products_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists scraped_products_updated_at_trigger on public.scraped_products;

create trigger scraped_products_updated_at_trigger
before update on public.scraped_products
for each row
execute function public.set_scraped_products_updated_at();

alter table public.scraped_products enable row level security;

revoke all on public.scraped_products from anon, authenticated;
grant all on public.scraped_products to service_role;
grant usage, select on sequence public.scraped_products_id_seq to service_role;

comment on table public.scraped_products is 'Raw product candidates scraped from external marketplace sources for admin review.';

create table if not exists public.scraping_source_settings (
  source text primary key,
  target_url text not null check (target_url ~* '^https?://'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.set_scraping_source_settings_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists scraping_source_settings_updated_at_trigger on public.scraping_source_settings;

create trigger scraping_source_settings_updated_at_trigger
before update on public.scraping_source_settings
for each row
execute function public.set_scraping_source_settings_updated_at();

alter table public.scraping_source_settings enable row level security;

revoke all on public.scraping_source_settings from anon, authenticated;
grant all on public.scraping_source_settings to service_role;

comment on table public.scraping_source_settings is 'Admin-managed target URLs for external scraping sources. Missing rows use application defaults.';
